# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/Documents/C++/Scop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/Documents/C++/Scop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/user/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/202.7660.37/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Documents/C++/Scop/CMakeFiles /home/user/Documents/C++/Scop/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/Documents/C++/Scop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Scop

# Build rule for target.
Scop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Scop
.PHONY : Scop

# fast build rule for target.
Scop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/build
.PHONY : Scop/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f libs/CMakeFiles/glad.dir/build.make libs/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f libs/glfw/CMakeFiles/uninstall.dir/build.make libs/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f libs/glfw/src/CMakeFiles/glfw.dir/build.make libs/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f libs/imgui/CMakeFiles/imgui.dir/build.make libs/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

libs/glad/src/glad.o: libs/glad/src/glad.c.o

.PHONY : libs/glad/src/glad.o

# target to build an object file
libs/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/glad/src/glad.c.o
.PHONY : libs/glad/src/glad.c.o

libs/glad/src/glad.i: libs/glad/src/glad.c.i

.PHONY : libs/glad/src/glad.i

# target to preprocess a source file
libs/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/glad/src/glad.c.i
.PHONY : libs/glad/src/glad.c.i

libs/glad/src/glad.s: libs/glad/src/glad.c.s

.PHONY : libs/glad/src/glad.s

# target to generate assembly for a file
libs/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/glad/src/glad.c.s
.PHONY : libs/glad/src/glad.c.s

libs/imgui/imgui.o: libs/imgui/imgui.cpp.o

.PHONY : libs/imgui/imgui.o

# target to build an object file
libs/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui.cpp.o
.PHONY : libs/imgui/imgui.cpp.o

libs/imgui/imgui.i: libs/imgui/imgui.cpp.i

.PHONY : libs/imgui/imgui.i

# target to preprocess a source file
libs/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui.cpp.i
.PHONY : libs/imgui/imgui.cpp.i

libs/imgui/imgui.s: libs/imgui/imgui.cpp.s

.PHONY : libs/imgui/imgui.s

# target to generate assembly for a file
libs/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui.cpp.s
.PHONY : libs/imgui/imgui.cpp.s

libs/imgui/imgui_draw.o: libs/imgui/imgui_draw.cpp.o

.PHONY : libs/imgui/imgui_draw.o

# target to build an object file
libs/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_draw.cpp.o
.PHONY : libs/imgui/imgui_draw.cpp.o

libs/imgui/imgui_draw.i: libs/imgui/imgui_draw.cpp.i

.PHONY : libs/imgui/imgui_draw.i

# target to preprocess a source file
libs/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_draw.cpp.i
.PHONY : libs/imgui/imgui_draw.cpp.i

libs/imgui/imgui_draw.s: libs/imgui/imgui_draw.cpp.s

.PHONY : libs/imgui/imgui_draw.s

# target to generate assembly for a file
libs/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_draw.cpp.s
.PHONY : libs/imgui/imgui_draw.cpp.s

libs/imgui/imgui_impl_glfw.o: libs/imgui/imgui_impl_glfw.cpp.o

.PHONY : libs/imgui/imgui_impl_glfw.o

# target to build an object file
libs/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_impl_glfw.cpp.o
.PHONY : libs/imgui/imgui_impl_glfw.cpp.o

libs/imgui/imgui_impl_glfw.i: libs/imgui/imgui_impl_glfw.cpp.i

.PHONY : libs/imgui/imgui_impl_glfw.i

# target to preprocess a source file
libs/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_impl_glfw.cpp.i
.PHONY : libs/imgui/imgui_impl_glfw.cpp.i

libs/imgui/imgui_impl_glfw.s: libs/imgui/imgui_impl_glfw.cpp.s

.PHONY : libs/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
libs/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_impl_glfw.cpp.s
.PHONY : libs/imgui/imgui_impl_glfw.cpp.s

libs/imgui/imgui_impl_opengl3.o: libs/imgui/imgui_impl_opengl3.cpp.o

.PHONY : libs/imgui/imgui_impl_opengl3.o

# target to build an object file
libs/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_impl_opengl3.cpp.o
.PHONY : libs/imgui/imgui_impl_opengl3.cpp.o

libs/imgui/imgui_impl_opengl3.i: libs/imgui/imgui_impl_opengl3.cpp.i

.PHONY : libs/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
libs/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_impl_opengl3.cpp.i
.PHONY : libs/imgui/imgui_impl_opengl3.cpp.i

libs/imgui/imgui_impl_opengl3.s: libs/imgui/imgui_impl_opengl3.cpp.s

.PHONY : libs/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
libs/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_impl_opengl3.cpp.s
.PHONY : libs/imgui/imgui_impl_opengl3.cpp.s

libs/imgui/imgui_widgets.o: libs/imgui/imgui_widgets.cpp.o

.PHONY : libs/imgui/imgui_widgets.o

# target to build an object file
libs/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_widgets.cpp.o
.PHONY : libs/imgui/imgui_widgets.cpp.o

libs/imgui/imgui_widgets.i: libs/imgui/imgui_widgets.cpp.i

.PHONY : libs/imgui/imgui_widgets.i

# target to preprocess a source file
libs/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_widgets.cpp.i
.PHONY : libs/imgui/imgui_widgets.cpp.i

libs/imgui/imgui_widgets.s: libs/imgui/imgui_widgets.cpp.s

.PHONY : libs/imgui/imgui_widgets.s

# target to generate assembly for a file
libs/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/imgui/imgui_widgets.cpp.s
.PHONY : libs/imgui/imgui_widgets.cpp.s

libs/stb_image/stb_image.o: libs/stb_image/stb_image.cpp.o

.PHONY : libs/stb_image/stb_image.o

# target to build an object file
libs/stb_image/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/stb_image/stb_image.cpp.o
.PHONY : libs/stb_image/stb_image.cpp.o

libs/stb_image/stb_image.i: libs/stb_image/stb_image.cpp.i

.PHONY : libs/stb_image/stb_image.i

# target to preprocess a source file
libs/stb_image/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/stb_image/stb_image.cpp.i
.PHONY : libs/stb_image/stb_image.cpp.i

libs/stb_image/stb_image.s: libs/stb_image/stb_image.cpp.s

.PHONY : libs/stb_image/stb_image.s

# target to generate assembly for a file
libs/stb_image/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/libs/stb_image/stb_image.cpp.s
.PHONY : libs/stb_image/stb_image.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/main.cpp.s
.PHONY : main.cpp.s

src/Shader.o: src/Shader.cpp.o

.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i

.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s

.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Texture.o: src/Texture.cpp.o

.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i

.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s

.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Scop.dir/build.make CMakeFiles/Scop.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... Scop"
	@echo "... glad"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... libs/glad/src/glad.o"
	@echo "... libs/glad/src/glad.i"
	@echo "... libs/glad/src/glad.s"
	@echo "... libs/imgui/imgui.o"
	@echo "... libs/imgui/imgui.i"
	@echo "... libs/imgui/imgui.s"
	@echo "... libs/imgui/imgui_draw.o"
	@echo "... libs/imgui/imgui_draw.i"
	@echo "... libs/imgui/imgui_draw.s"
	@echo "... libs/imgui/imgui_impl_glfw.o"
	@echo "... libs/imgui/imgui_impl_glfw.i"
	@echo "... libs/imgui/imgui_impl_glfw.s"
	@echo "... libs/imgui/imgui_impl_opengl3.o"
	@echo "... libs/imgui/imgui_impl_opengl3.i"
	@echo "... libs/imgui/imgui_impl_opengl3.s"
	@echo "... libs/imgui/imgui_widgets.o"
	@echo "... libs/imgui/imgui_widgets.i"
	@echo "... libs/imgui/imgui_widgets.s"
	@echo "... libs/stb_image/stb_image.o"
	@echo "... libs/stb_image/stb_image.i"
	@echo "... libs/stb_image/stb_image.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

